POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "What a blog",
    "author": "Muhammad Ali Gulzar",
    "url": "localhost",
    "likes": 2,
    "userId": "5fa17191f34b6b6993850a02"
}